#ifndef __VectorGraphicsInterpreterCircleDialog__
#define __VectorGraphicsInterpreterCircleDialog__

/**
@file
Subclass of CircleDialog, which is generated by wxFormBuilder.
*/

//// end generated include

#include "../GUI/GUI.h"
#include "../Shapes/Circle.h"
#include "DialogValidator.h"

/** Implementing CircleDialog */
class VectorGraphicsInterpreterCircleDialog : public CircleDialog
{
	protected:
		// Handlers for CircleDialog events.
		void m_centerOnTextEnter( wxCommandEvent& event );
		void m_radiusOnTextEnter( wxCommandEvent& event );
		void m_colourOnTextEnter( wxCommandEvent& event );
		void m_fillColourOnTextEnter( wxCommandEvent& event );
		void m_transformVectorOnTextEnter( wxCommandEvent& event );
		void m_rotationAngleOnTextEnter( wxCommandEvent& event );
		void m_deleteButtonOnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		VectorGraphicsInterpreterCircleDialog( wxWindow* parent );
	//// end generated class members
	
	private:
		/** pointer to circle */
		ShapeCircle* m_circle;
		/** dialog validator */
		DialogValidator m_validator;

	public:
		/** Constructor connected with specific circle shape */
		VectorGraphicsInterpreterCircleDialog(wxWindow* parent, ShapeCircle* circle);

};

#endif // __VectorGraphicsInterpreterCircleDialog__
