#ifndef __VectorGraphicsInterpreterEllipseDialog__
#define __VectorGraphicsInterpreterEllipseDialog__

/**
@file
Subclass of EllipseDialog, which is generated by wxFormBuilder.
*/

//// end generated include

#include "../GUI/GUI.h"
#include "../Shapes/Ellipse.h"
#include "DialogValidator.h"


/** Implementing EllipseDialog */
class VectorGraphicsInterpreterEllipseDialog : public EllipseDialog
{
	protected:
		// Handlers for EllipseDialog events.
		void m_centerOnTextEnter( wxCommandEvent& event );
		void m_horizontalShaftOnTextEnter( wxCommandEvent& event );
		void m_verticalShaftOnTextEnter( wxCommandEvent& event );
		void m_colourOnTextEnter( wxCommandEvent& event );
		void m_fillColourOnTextEnter( wxCommandEvent& event );
		void m_transformVectorOnTextEnter( wxCommandEvent& event );
		void m_rotationAngleOnTextEnter( wxCommandEvent& event );
		void m_deleteButtonOnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		VectorGraphicsInterpreterEllipseDialog( wxWindow* parent );
	//// end generated class members
	
	private:
		/** pointer to ellipse */
		ShapeEllipse* m_ellipse;
		/** dialog validator */
		DialogValidator m_validator;

	public:
		/** Constructor connected with specific ellipse shape */
		VectorGraphicsInterpreterEllipseDialog(wxWindow* parent, ShapeEllipse* ellipse);

};

#endif // __VectorGraphicsInterpreterEllipseDialog__
