#ifndef __VectorGraphicsInterpreterLineDialog__
#define __VectorGraphicsInterpreterLineDialog__

/**
@file
Subclass of LineDialog, which is generated by wxFormBuilder.
*/

#include "../GUI/GUI.h"
#include "../Shapes/Line.h"

//// end generated include

/** Implementing LineDialog */
class VectorGraphicsInterpreterLineDialog : public LineDialog
{
	protected:
		// Handlers for LineDialog events.
		void m_startPointOnTextEnter( wxCommandEvent& event );
		void m_endPointOnTextEnter( wxCommandEvent& event );
		void m_colourOnTextEnter( wxCommandEvent& event );
		void m_transformVectorOnTextEnter( wxCommandEvent& event );
		void m_rotationAngleOnTextEnter( wxCommandEvent& event );
		void m_deleteButtonOnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		VectorGraphicsInterpreterLineDialog( wxWindow* parent );
	//// end generated class members

		/** Constructor connected with specific line shape */
		VectorGraphicsInterpreterLineDialog( wxWindow* parent, ShapeLine* line );

	private:
		ShapeLine* m_line;

};

#endif // __VectorGraphicsInterpreterLineDialog__
