#ifndef __VectorGraphicsInterpreterGUI__
#define __VectorGraphicsInterpreterGUI__

/**
@file
Subclass of GUI, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include <wx/dc.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <wx/textfile.h>
#include <wx/filedlg.h>
#include <fstream>
#include <sstream>
#include <vector>
#include <thread>
#include <chrono>
#include <array>
#include <cstdio>

#include "../Panel/Panel.h"
#include "../Shapes/Line.h"
#include "../Shapes/Rectangle.h"
#include "../Shapes/Circle.h"
#include "../Shapes/Ellipse.h"
#include "../Shapes/Arc.h"
#include "../CommandValidator/CommandValidator.h"
#include "../Dialogs/VectorGraphicsInterpreterLineDialog.h"

/** Implementing GUI */
class VectorGraphicsInterpreterGUI : public GUI
{
protected:
	// Handlers for GUI events.
	void workspaceOnMotion(wxMouseEvent& event);
	void workspaceOnUpdateUI(wxUpdateUIEvent& event);
	void consoleOnTextEnter(wxCommandEvent& event);
	void m_objectsListOnLeaveWindow(wxMouseEvent& event);
	void m_objectsListOnListBox(wxCommandEvent& event);
	void OnRightDown(wxMouseEvent& event);
public:
	/** Constructor */
	VectorGraphicsInterpreterGUI(wxWindow* parent);
	//// end generated class members
	/** Destructor */
	~VectorGraphicsInterpreterGUI();



private:

	/** array of shape instances */
	std::array<unsigned, 5> m_shapesCounter{1, 1, 1, 1, 1};
	
	std::vector <Shape*> m_shapes;
	Panel m_drawPanel;
	//do zapisu pliku z informacja o obiekcie
	std::string m_cmdBuffer;

	


	/** command validator */
	CommandValidator m_commandValidator;
	/** current x position on workspace */
	int m_currentX = 0;
	/** current y position on workspace */
	int m_currentY = 0;
	/** bitmap used in order to save to file */
	wxBitmap m_picture;

	wxCoord m_bitMapWidth = 2000;
	wxCoord m_bitMapHeight = 2000;
	/** number of lines in console */
	unsigned long m_consoleLines = 0;

	/** console commands */
	void commandRange();
	void commandBackground();
	void commandLine();
	void commandRectangle();
	void commandCircle();
	void commandEllipse();
	void commandArc();
	void commandFill();
	void commandDelete();
	void commandMove();
	void commandRotate();
	void commandShow();
	void commandClear();
	void commandWrite();
	void commandRead();
	void commandSave();
	void commandClearcmd();

	/**
	 * command highilighting object for 0.5s
	 * @param object id / -1 if all
	 */
	void show(int id);

public:

	/**
	 * method painting workspace
	 */
	void Repaint();
























};

#endif // __VectorGraphicsInterpreterGUI__
