#ifndef __VectorGraphicsInterpreterGUI__
#define __VectorGraphicsInterpreterGUI__

/**
@file
Subclass of GUI, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include <wx/dc.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <vector>

#include "../Panel/Panel.h"
#include "../Shapes/Line.h"
#include "../CommandValidator/CommandValidator.h"

/** Implementing GUI */
class VectorGraphicsInterpreterGUI : public GUI
{
	protected:
		// Handlers for GUI events.
		void workspaceOnMotion( wxMouseEvent& event );
		void workspaceOnUpdateUI( wxUpdateUIEvent& event );
		void consoleOnTextEnter( wxCommandEvent& event );
	public:
		/** Constructor */
		VectorGraphicsInterpreterGUI( wxWindow* parent );
	//// end generated class members



private:
	std::vector <Shape*> m_shapes;
	Panel m_drawPanel;

	/** command validator */
	CommandValidator m_commandValidator;
	/** current x position on workspace */
	int m_currentX = 0;
	/** current y position on workspace */
	int m_currentY = 0;
	/** bitmap used in order to save to file */
	wxBitmap m_picture;
	/** number of lines in console */
	unsigned long m_consoleLines = 0;

	/** console commands */
	void commandRange();
	void commandBackground();
	void commandLine();
	void commandRectangle();
	void commandCircle();
	void commandEllipse();
	void commandArc();
	void commandFill();
	void commandDelete();
	void commandMove();
	void commandRotate();
	void commandShow();
	void commandClear();
	void commandWrite();
	void commandRead();
	void commandSave();
	void commandClearcmd();

public:
	/**
	 * method painting workspace
	 */
	void Repaint();
























};

#endif // __VectorGraphicsInterpreterGUI__
