#ifndef __VectorGraphicsInterpreterGUI__
#define __VectorGraphicsInterpreterGUI__

/**
@file
Subclass of GUI, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

/** Implementing GUI */
class VectorGraphicsInterpreterGUI : public GUI
{
	protected:
		// Handlers for GUI events.
		void m_consoleOnTextEnter( wxCommandEvent& event );
	public:
		/** Constructor */
		VectorGraphicsInterpreterGUI( wxWindow* parent );
	//// end generated class members

























};

#endif // __VectorGraphicsInterpreterGUI__
